"""cities_column

Revision ID: 1c140f481ea5
Revises: 4be659b1e34b
Create Date: 2024-02-03 16:10:58.796980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c140f481ea5'
down_revision: Union[str, None] = '4be659b1e34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clubs', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('city_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'organizations', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    # ### end Alembic commands ###
